# Generated by Django 5.1.15 on 2026-07-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoNido',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_ubicacion', models.CharField(choices=[('roca', 'Roca'), ('arbol', 'Árbol'), ('edificio', 'Edificio'), ('poste', 'Poste'), ('acantilado', 'Acantilado'), ('otro', 'Otro')], max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grupo de nidos',
                'verbose_name_plural': 'Grupos de nidos',
                'db_table': 'grupos_nidos',
            },
        ),
        migrations.CreateModel(
            name='Nido',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('codigo_en_grupo', models.CharField(blank=True, max_length=50, null=True)),
                ('posicion_en_grupo', models.CharField(blank=True, max_length=150, null=True)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_descubrimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('destruido', 'Destruido'), ('retirado', 'Retirado')], default='activo', max_length=20)),
                ('fecha_estado', models.DateField(blank=True, null=True)),
                ('motivo_estado', models.TextField(blank=True, null=True)),
                ('metodo_ubicacion', models.CharField(choices=[('manual_mapa', 'Manual mapa'), ('gps_movil', 'GPS móvil'), ('importado', 'Importado')], default='manual_mapa', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nido',
                'verbose_name_plural': 'Nidos',
                'db_table': 'nidos',
            },
        ),
    ]
