# Generated by Django 5.1.15 on 2026-07-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoNido',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_evento', models.DateTimeField()),
                ('tipo_evento', models.CharField(choices=[('cambio_estado', 'Cambio de estado'), ('revision', 'Revisión'), ('incidencia', 'Incidencia'), ('mantenimiento', 'Mantenimiento'), ('otro', 'Otro')], max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_nuevo', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Evento de nido',
                'verbose_name_plural': 'Eventos de nidos',
                'db_table': 'eventos_nido',
            },
        ),
    ]
