# Generated by Django 5.1.15 on 2026-07-13 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('nests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventonido',
            name='nido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='nests.nido'),
        ),
    ]
