# Generated by Django 5.1.15 on 2026-07-13 16:53

import apps.mediafiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenNido',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('archivo', models.ImageField(upload_to=apps.mediafiles.models.ruta_imagen_nido)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagen de nido',
                'verbose_name_plural': 'Imágenes de nidos',
                'db_table': 'imagenes_nido',
            },
        ),
    ]
