# Generated by Django 5.1.15 on 2026-07-13 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediafiles', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imagennido',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='imagennido',
            constraint=models.UniqueConstraint(condition=models.Q(('es_principal', True)), fields=('nido',), name='unique_imagen_principal_por_nido'),
        ),
    ]
