# Generated by Django 5.1.15 on 2026-07-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_comun', models.CharField(max_length=150)),
                ('nombre_cientifico', models.CharField(blank=True, max_length=150, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
                'db_table': 'especies',
            },
        ),
    ]
