# Generated by Django 5.1.15 on 2026-07-13 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nests', '0001_initial'),
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionNido',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_observacion', models.DateField()),
                ('ocupado', models.BooleanField(default=False)),
                ('hay_huevos', models.BooleanField(default=False)),
                ('cantidad_huevos', models.PositiveIntegerField(default=0)),
                ('hay_polluelos', models.BooleanField(default=False)),
                ('cantidad_polluelos', models.PositiveIntegerField(default=0)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('especie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones', to='species.especie')),
                ('nido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='nests.nido')),
            ],
            options={
                'verbose_name': 'Observación de nido',
                'verbose_name_plural': 'Observaciones de nidos',
                'db_table': 'observaciones_nido',
            },
        ),
    ]
